# 1.入门

In [5]:
import torch

In [6]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape

torch.Size([12])

In [8]:
x.numel()  # NUM of ELements in x

12

In [9]:
x.reshape(3, 4)  # 注意效果为返回而不是直接作用

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
x.reshape(3, -1)  # -1：自动计算缺省维度

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros(2, 3, 4)  # 注意返回float

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)  # 生成指定形状的元素~N(0,1)的tensor

tensor([[-1.5224,  1.2475, -0.3750, -0.7070],
        [ 0.1561, -1.2448, -0.1454,  0.3468],
        [-0.5844,  1.1650, -0.0701,  0.7290]])

In [14]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# 2.运算符

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # 按元素运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X = torch.arange(12, dtype = torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y # 逐元素比较

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum(), X.square()

(tensor(66.),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]]))

# 3.广播机制

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b # 广播

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 4.索引&切片

In [21]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
X[1, 2]
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[:, 0:2] = 114
X

tensor([[114., 114.,   2.,   3.],
        [114., 114.,   9.,   7.],
        [114., 114.,  10.,  11.]])

# 5.节省内存

In [24]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

Z[:] = X + Y    # 原地加法
print('id(Z):', id(Z))

Z = X + Y       # 浪费空间
print('id(Z):', id(Z))

id(Z): 140166992358752
id(Z): 140166992358752
id(Z): 140162960636400


# 6.转换为其他Python对象

In [25]:
A = X.numpy() # tensor -> numpy
B = torch.tensor(A) # numpy -> tensor
A, B

(array([[114., 114.,   2.,   3.],
        [114., 114.,   9.,   7.],
        [114., 114.,  10.,  11.]], dtype=float32),
 tensor([[114., 114.,   2.,   3.],
         [114., 114.,   9.,   7.],
         [114., 114.,  10.,  11.]]))

In [26]:
a = torch.tensor([2.29]) # scale -> tensor, 注意[]
b = a.item() # tensor -> scale
a, b

(tensor([2.2900]), 2.2899999618530273)