In [1]:
import torch

True

In [41]:
A = torch.tensor([[1,2,3], [4,5,6]])
A+1, A.T, A.sum(), \
    A.sum(axis=0)   # 沿axis=0轴求和, axis=1轴消失

(tensor([[2, 3, 4],
         [5, 6, 7]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor(21),
 tensor([5, 7, 9]))

In [19]:
x = torch.randn(4)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)   # 点积

(tensor([1.5491, 0.3958, 0.1352, 2.1792]),
 tensor([1., 1., 1., 1.]),
 tensor(4.2593))

In [31]:
''' Matrix * Vector '''
A = torch.arange(0, 12, dtype=torch.float32).reshape(3, 4)
A, x, torch.mv(A, x)    # dtype相同（注意是torch.XX）才能相乘，左列=右行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([1.5491, 0.3958, 0.1352, 2.1792]),
 tensor([ 7.2038, 24.2410, 41.2782]))

In [37]:
''' Matrix * Matrix '''
torch.mm(A, A.T)

tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])

In [40]:
'''L1&L2 norm'''
A.abs().sum(), A.norm()

(tensor(66.), tensor(22.4944))